name = "ゴーストルール"
name_en = "Ghost Rule"
prod = "DECO*27"
prod_en = "DECO*27"
song_path = "beatmaps/ゴーストルール/ゴーストルール.mp3"
lite_song_path = "beatmaps/ゴーストルール/ゴーストルールLITE.mp3"
lite_img = "beatmaps/ゴーストルール/images/lite.jpg"
questionable = true
bpm_crotchet = 105
bpm_semiquaver = 420
bpm_semihemiquaver = 840

[vocals]
vocaloid = "初音ミク"
vocaloid_avatar = "beatmaps/ゴーストルール/images/vocaloid_avatar.jpg"
cover = ""
cover_avatar = "beatmaps/ゴーストルール/images/cover_avatar.jpg"

[mv]
available = false
frames_path = "beatmaps/ゴーストルール/frames"

[difficulty]
easy = 4
normal = 11
hard = 19
# expert = 26
master = 26

# Normal mode
[notes]
1=[{l=1, w=1, t='t'}]
